import { extraScenarioPoints } from "./scenario-points-extra.js";
import type { HistoricalEvent, HistoricalScenario } from "./scenario-data.js";

const PRICE_SOURCE = "https://developers.binance.com/docs/binance-spot-api-docs/rest-api/market-data-endpoints#klinecandlestick-data";
const DATA_SOURCE = {
  name: "Binance: дневное закрытие в USDT; перевод в рубли по официальному курсу Банка России",
  url: PRICE_SOURCE,
  retrievedAt: "2026-08-17T09:00:00Z",
};

const asset = (scenarioId: string, symbol: "BTC" | "ETH" | "SOL", name: string, color: string) => ({
  symbol,
  name,
  color,
  points: extraScenarioPoints[scenarioId]?.[symbol] ?? [],
});

const marketEvent = (
  id: string,
  at: string,
  title: string,
  summary: string,
  context: string,
  affectedAssets: string[],
): HistoricalEvent => ({
  id,
  at,
  title,
  summary,
  context,
  category: "MARKET",
  affectedAssets,
  sourceName: "Binance, дневные рыночные данные",
  sourceUrl: PRICE_SOURCE,
});

export const extraHistoricalScenarios: HistoricalScenario[] = [
  {
    id: "boom-2017-2018",
    version: "1.0.0",
    title: "Первый криптобум и резкое падение",
    description: "2017–2018: быстрый рост, громкие обещания, страх упустить прибыль и долгая проверка терпения.",
    startAt: "2017-08-17T00:00:00Z",
    endAt: "2018-12-31T00:00:00Z",
    startingBalanceRub: 100_000,
    difficulty: "INTERMEDIATE",
    educationalFocus: ["Замечать страх упустить рост", "Не путать популярность с надёжностью", "Переживать длинное падение по заранее выбранному плану"],
    benchmark: { kind: "BUY_AND_HOLD", assetSymbol: "BTC", label: "Купить Bitcoin в начале и держать" },
    durationMs: 6 * 60_000,
    assets: [asset("boom-2017-2018", "BTC", "Bitcoin", "#f5a13a"), asset("boom-2017-2018", "ETH", "Ethereum", "#718bd5")],
    events: [
      {
        id: "china-ico-ban-2017", at: "2017-09-04T00:00:00Z", title: "Китай запретил привлечение денег через ICO",
        summary: "Власти назвали такой сбор денег незаконным и потребовали остановить новые размещения токенов.",
        context: "Запрет касается способа привлечения денег, но рынок часто сначала продаёт всё подряд. Важно отделять конкретный объект новости от общей паники.",
        category: "REGULATION", affectedAssets: ["BTC", "ETH"], sourceName: "Государственная канцелярия интернет-информации КНР", sourceUrl: "https://www.cac.gov.cn/2017-09/04/c_1121603512.htm",
      },
      {
        id: "byzantium-2017", at: "2017-10-16T00:00:00Z", title: "Ethereum провёл обновление Byzantium",
        summary: "Сеть получила технические улучшения, а награда за блок уменьшилась с 5 до 3 ETH.",
        context: "Работающее обновление — признак развития сети. Но технический успех не обещает немедленного роста цены.",
        category: "TECHNOLOGY", affectedAssets: ["ETH"], sourceName: "Ethereum Foundation", sourceUrl: "https://blog.ethereum.org/2017/10/12/byzantium-hf-announcement",
      },
      {
        id: "sec-ico-warning-2017", at: "2017-11-01T00:00:00Z", title: "SEC предупредила о рекламе токенов знаменитостями",
        summary: "Регулятор напомнил: известное лицо может получать деньги за рекламу и не раскрывать риски предложения.",
        context: "Популярность автора не заменяет проверку проекта. Реклама отвечает на вопрос «кто рассказал», а не «куда ушли деньги и что защищает покупателя».",
        category: "REGULATION", affectedAssets: ["BTC", "ETH"], sourceName: "U.S. Securities and Exchange Commission", sourceUrl: "https://www.sec.gov/newsroom/press-releases/2017-219",
      },
      {
        id: "bitcoin-futures-certified", at: "2017-12-01T00:00:00Z", title: "Биржи подготовили первые регулируемые фьючерсы на Bitcoin",
        summary: "CME и Cboe сообщили регулятору о запуске контрактов, цена которых связана с Bitcoin.",
        context: "Такой инструмент даёт крупным участникам больше способов работать с ценой — и на рост, и на падение. Это не односторонний сигнал.",
        category: "MARKET", affectedAssets: ["BTC"], sourceName: "U.S. Commodity Futures Trading Commission", sourceUrl: "https://www.cftc.gov/PressRoom/PressReleases/7654-17",
      },
      marketEvent("bitcoin-peak-2017", "2017-12-17T00:00:00Z", "Bitcoin подошёл к вершине первого большого бума", "После стремительного роста цена оказалась около 20 000 долларов, а интерес новичков стал особенно высоким.", "Самая убедительная история о будущем часто появляется после уже случившегося роста. Чем сильнее ажиотаж, тем важнее ограничить размер решения.", ["BTC", "ETH"]),
      {
        id: "coincheck-hack", at: "2018-01-26T00:00:00Z", title: "У Coincheck похитили клиентские криптоактивы",
        summary: "После несанкционированного доступа с площадки ушли монеты NEM клиентов; японский регулятор начал проверку.",
        context: "Риск площадки — не то же самое, что риск самой сети. Даже если цена актива не упала, потеря доступа у посредника может быть полной.",
        category: "SECURITY", affectedAssets: ["BTC", "ETH", "NEM"], sourceName: "Financial Services Agency of Japan", sourceUrl: "https://www.fsa.go.jp/en/conference/minister/2018/20180202.html",
      },
      {
        id: "sec-platform-warning-2018", at: "2018-03-07T00:00:00Z", title: "SEC предупредила о статусе криптоплощадок",
        summary: "Регулятор объяснил, что слово «биржа» в названии ещё не означает государственную регистрацию и защиту клиента.",
        context: "Удобный интерфейс не показывает, кто хранит активы, как исполняются сделки и что произойдёт при сбое. Эти вопросы надо задавать до перевода денег.",
        category: "REGULATION", affectedAssets: ["BTC", "ETH"], sourceName: "U.S. Securities and Exchange Commission", sourceUrl: "https://www.sec.gov/newsroom/speeches-statements/enforcement-tm-statement-potentially-unlawful-online-platforms-trading-digital-assets",
      },
      {
        id: "hinman-ether-speech", at: "2018-06-14T00:00:00Z", title: "Представитель SEC высказался о текущих продажах Ether",
        summary: "В публичной речи директор SEC сказал, что применение режима ценных бумаг к текущим сделкам с Ether, по его мнению, даёт мало пользы.",
        context: "Речь сотрудника помогает понять подход, но не равна новому закону. Юридические выводы всегда зависят от конкретных условий продажи.",
        category: "REGULATION", affectedAssets: ["ETH"], sourceName: "U.S. Securities and Exchange Commission", sourceUrl: "https://www.sec.gov/newsroom/speeches-statements/speech-hinman-061418",
      },
      {
        id: "winklevoss-rejected", at: "2018-07-26T00:00:00Z", title: "SEC снова не разрешила биржевой продукт на Bitcoin",
        summary: "Комиссия отклонила предложение по Winklevoss Bitcoin Trust, сославшись на риски манипуляций и надзора.",
        context: "Отказ одному продукту не запрещает сам Bitcoin. Но он показывает, что путь к привычным биржевым инструментам может занимать годы.",
        category: "REGULATION", affectedAssets: ["BTC"], sourceName: "Federal Register", sourceUrl: "https://www.govinfo.gov/content/pkg/FR-2018-08-01/pdf/2018-16427.pdf",
      },
      marketEvent("crypto-winter-low-2018", "2018-12-15T00:00:00Z", "Падение затянулось почти на весь год", "Bitcoin стоил примерно на 80% ниже вершины, а многие небольшие токены потеряли ещё больше.", "Долгое падение проверяет план сильнее, чем один плохой день. Если допустимый убыток не определён заранее, решение начинает диктовать усталость.", ["BTC", "ETH"]),
    ],
    dataSource: DATA_SOURCE,
  },
  {
    id: "winter-2021-2022",
    version: "1.0.0",
    title: "Эйфория, крах проектов и криптозима",
    description: "2021–2022: рекорды сменяются закрытыми выводами, разрушением громких проектов и дорогими деньгами.",
    startAt: "2021-03-01T00:00:00Z",
    endAt: "2023-01-01T00:00:00Z",
    startingBalanceRub: 100_000,
    difficulty: "ADVANCED",
    educationalFocus: ["Различать риск актива и посредника", "Не гнаться за доходностью без объяснения её источника", "Сохранять запас денег при сильной неопределённости"],
    benchmark: { kind: "BUY_AND_HOLD", assetSymbol: "BTC", label: "Купить Bitcoin в начале и держать" },
    durationMs: 7 * 60_000,
    assets: [asset("winter-2021-2022", "BTC", "Bitcoin", "#f5a13a"), asset("winter-2021-2022", "ETH", "Ethereum", "#718bd5"), asset("winter-2021-2022", "SOL", "Solana", "#6f52e5")],
    events: [
      {
        id: "coinbase-listing", at: "2021-04-14T00:00:00Z", title: "Coinbase вышла на фондовую биржу",
        summary: "Акции крупной криптоплощадки начали торговаться на Nasdaq через прямой листинг.",
        context: "Выход компании на биржу усиливает внимание к отрасли, но акция площадки и криптоактив — разные вложения с разными рисками.",
        category: "COMPANY", affectedAssets: ["BTC", "ETH"], sourceName: "Coinbase Investor Relations", sourceUrl: "https://investor.coinbase.com/news/news-details/2021/Coinbase-Announces-Effectiveness-of-Registration-Statement-and-Anticipated-Listing-Date-of-its-Class-A-Common-Stock-on-the-Nasdaq-Global-Select-Market/default.aspx",
      },
      {
        id: "tesla-pauses-bitcoin", at: "2021-05-12T00:00:00Z", title: "Tesla остановила оплату автомобилей в Bitcoin",
        summary: "Компания приостановила недолго работавший способ оплаты; рынок резко отреагировал на смену позиции заметной компании.",
        context: "Одна компания может быстро изменить решение. Если покупка держится только на чужом обещании, у владельца нет собственного плана.",
        category: "COMPANY", affectedAssets: ["BTC", "ETH", "SOL"], sourceName: "Tesla, квартальный отчёт в SEC", sourceUrl: "https://www.sec.gov/Archives/edgar/data/1318605/000095017021000524/tsla-20210630.htm",
      },
      marketEvent("may-crash-2021", "2021-05-19T00:00:00Z", "Рынок потерял значительную часть роста за несколько дней", "Bitcoin кратко опускался примерно вдвое от апрельской вершины, а другие активы двигались ещё резче.", "После быстрого падения хочется либо продать всё, либо немедленно купить «со скидкой». Оба импульса стоит проверить лимитами и запасом денег.", ["BTC", "ETH", "SOL"]),
      {
        id: "el-salvador-bitcoin-law", at: "2021-06-09T00:00:00Z", title: "Сальвадор принял закон о Bitcoin",
        summary: "Страна признала Bitcoin законным платёжным средством наряду с долларом США.",
        context: "Государственное решение расширяет возможное использование, но не отменяет колебания цены, технические трудности и право других стран выбрать иной подход.",
        category: "REGULATION", affectedAssets: ["BTC"], sourceName: "Asamblea Legislativa de El Salvador", sourceUrl: "https://www.asamblea.gob.sv/taxonomy/term/933",
      },
      {
        id: "london-upgrade", at: "2021-08-05T00:00:00Z", title: "Ethereum изменил расчёт комиссии",
        summary: "Обновление London включило EIP-1559: базовая часть комиссии стала сжигаться, а её расчёт — более предсказуемым.",
        context: "Изменение правил предложения важно для долгого срока, но цена зависит не только от выпуска монет — ещё от спроса, конкуренции и общего рынка.",
        category: "TECHNOLOGY", affectedAssets: ["ETH"], sourceName: "Ethereum Foundation", sourceUrl: "https://blog.ethereum.org/2021/07/15/london-mainnet-announcement",
      },
      marketEvent("market-peak-2021", "2021-11-10T00:00:00Z", "Bitcoin и Ethereum обновили исторические максимумы", "После месяцев восстановления рынок снова оказался в центре внимания, а уверенность в продолжении роста была высокой.", "Максимум виден только задним числом. На вершине полезнее не угадывать день разворота, а проверить долю одного актива и план выхода.", ["BTC", "ETH", "SOL"]),
      {
        id: "fed-first-hike-2022", at: "2022-03-16T00:00:00Z", title: "ФРС начала повышать ставку",
        summary: "Центральный банк США поднял ставку с почти нулевого уровня и сообщил, что дальнейшие повышения вероятны.",
        context: "Когда безопасные инструменты начинают приносить больше, часть денег уходит из рискованных активов. Это давление может длиться дольше одной новости.",
        category: "WORLD", affectedAssets: ["BTC", "ETH", "SOL"], sourceName: "Federal Reserve", sourceUrl: "https://www.federalreserve.gov/newsevents/pressreleases/monetary20220316a.htm",
      },
      {
        id: "terra-collapse", at: "2022-05-09T00:00:00Z", title: "TerraUSD потерял привязку к доллару",
        summary: "Алгоритмический стейблкоин UST перестал держать цену около одного доллара; связанный токен LUNA быстро обесценился.",
        context: "Слово «стабильный» не объясняет механизм защиты цены. Нужно понимать, какие резервы есть и что произойдёт при массовом выходе пользователей.",
        category: "SECURITY", affectedAssets: ["BTC", "ETH", "SOL", "UST", "LUNA"], sourceName: "SEC, материалы дела Terraform Labs", sourceUrl: "https://www.sec.gov/files/terraform-labs-pte-ltd-amended-complaint.pdf",
      },
      {
        id: "celsius-withdrawals", at: "2022-06-12T00:00:00Z", title: "Celsius остановил вывод клиентских средств",
        summary: "Криптокредитор сослался на тяжёлые рыночные условия и поставил на паузу вывод, обмен и переводы.",
        context: "Высокий процент — плата за риск, даже если он не виден в приложении. Если посредник держит ключи, доступ к активу зависит от его платёжеспособности.",
        category: "COMPANY", affectedAssets: ["BTC", "ETH"], sourceName: "U.S. Commodity Futures Trading Commission", sourceUrl: "https://www.cftc.gov/media/8956/enfcelsiuscomplaint071323/download",
      },
      {
        id: "ethereum-merge", at: "2022-09-15T00:00:00Z", title: "Ethereum перешёл на Proof of Stake",
        summary: "Сеть завершила The Merge и отказалась от прежнего способа подтверждения блоков с помощью майнинга.",
        context: "Большое обновление может пройти успешно, а цена всё равно снизиться из-за общего рынка. Технологический результат и результат сделки — разные вещи.",
        category: "TECHNOLOGY", affectedAssets: ["ETH"], sourceName: "ethereum.org", sourceUrl: "https://ethereum.org/roadmap/merge/",
      },
      {
        id: "ftx-bankruptcy", at: "2022-11-11T00:00:00Z", title: "FTX и связанные компании подали на банкротство",
        summary: "Одна из крупнейших площадок не смогла выполнить требования клиентов после быстрого оттока средств.",
        context: "Размер, реклама и известные инвесторы не заменяют прозрачное хранение клиентских денег. Диверсифицировать нужно не только активы, но и места хранения.",
        category: "SECURITY", affectedAssets: ["BTC", "ETH", "SOL"], sourceName: "U.S. Commodity Futures Trading Commission", sourceUrl: "https://www.cftc.gov/About/HistoryoftheCFTC/history_2020s.html",
      },
      marketEvent("winter-low-2022", "2022-11-21T00:00:00Z", "Рынок обновил минимум после краха FTX", "Недоверие распространилось на другие площадки и проекты; продажи затронули даже активы, не связанные с FTX напрямую.", "После цепочки плохих новостей бездействие может быть разумным решением. Оно отличается от растерянности, если у него есть срок и условие пересмотра.", ["BTC", "ETH", "SOL"]),
    ],
    dataSource: DATA_SOURCE,
  },
  {
    id: "recovery-2023-2024",
    version: "1.0.0",
    title: "Восстановление и ожидание больших денег",
    description: "2023–2024: рынок оживает, суды и регуляторы меняют ожидания, а новые максимумы снова вызывают FOMO.",
    startAt: "2023-01-01T00:00:00Z",
    endAt: "2025-01-01T00:00:00Z",
    startingBalanceRub: 100_000,
    difficulty: "INTERMEDIATE",
    educationalFocus: ["Не покупать только из-за ожиданий", "Отличать решение регулятора от слуха", "Пересматривать доли после сильного роста"],
    benchmark: { kind: "BUY_AND_HOLD", assetSymbol: "BTC", label: "Купить Bitcoin в начале и держать" },
    durationMs: 7 * 60_000,
    assets: [asset("recovery-2023-2024", "BTC", "Bitcoin", "#f5a13a"), asset("recovery-2023-2024", "ETH", "Ethereum", "#718bd5"), asset("recovery-2023-2024", "SOL", "Solana", "#6f52e5")],
    events: [
      {
        id: "svb-failure", at: "2023-03-10T00:00:00Z", title: "Silicon Valley Bank был закрыт",
        summary: "После быстрого оттока вкладов американские власти закрыли банк и передали его под управление FDIC.",
        context: "Проблема обычного банка может задеть крипторынок через компании и резервы стейблкоинов. Связи между рынками становятся заметны во время стресса.",
        category: "WORLD", affectedAssets: ["BTC", "ETH", "SOL", "USDC"], sourceName: "Federal Deposit Insurance Corporation", sourceUrl: "https://www.fdic.gov/news/press-releases/2023/pr23016.html",
      },
      {
        id: "shapella", at: "2023-04-12T00:00:00Z", title: "Ethereum разрешил вывод монет из стейкинга",
        summary: "Обновление Shapella позволило валидаторам выводить ранее заблокированный ETH.",
        context: "Рынок мог бояться массовых продаж, но возможность вывода также снижает риск участия. Одно изменение может иметь противоположные последствия.",
        category: "TECHNOLOGY", affectedAssets: ["ETH"], sourceName: "Ethereum Foundation", sourceUrl: "https://blog.ethereum.org/2023/03/28/shapella-mainnet-announcement",
      },
      {
        id: "sec-binance-2023", at: "2023-06-05T00:00:00Z", title: "SEC предъявила претензии Binance",
        summary: "Регулятор подал иск против Binance и её основателя, выдвинув обвинения по работе площадок и ряду продуктов.",
        context: "Иск — это начало разбирательства, а не готовый приговор. Для пользователя он всё равно повышает риск хранения средств у затронутого посредника.",
        category: "REGULATION", affectedAssets: ["BTC", "ETH", "SOL"], sourceName: "U.S. Securities and Exchange Commission", sourceUrl: "https://www.sec.gov/newsroom/press-releases/2023-101-sec-files-13-charges-against-binance-entities-founder-changpeng-zhao",
      },
      {
        id: "sec-coinbase-2023", at: "2023-06-06T00:00:00Z", title: "SEC подала иск против Coinbase",
        summary: "Регулятор заявил, что площадка выполняла несколько функций рынка без требуемой регистрации.",
        context: "Две похожие новости подряд могут казаться полным запретом отрасли, хотя каждое дело имеет свои требования и долгий путь через суд.",
        category: "REGULATION", affectedAssets: ["BTC", "ETH", "SOL"], sourceName: "U.S. Securities and Exchange Commission", sourceUrl: "https://www.sec.gov/newsroom/press-releases/2023-102",
      },
      {
        id: "grayscale-court-win", at: "2023-08-29T00:00:00Z", title: "Суд отменил отказ SEC по заявке Grayscale",
        summary: "Апелляционный суд решил, что SEC недостаточно объяснила разное отношение к похожим продуктам на Bitcoin.",
        context: "Суд не запустил фонд автоматически. Он обязал регулятора заново рассмотреть решение — рынок торговал ожидание следующего шага.",
        category: "REGULATION", affectedAssets: ["BTC"], sourceName: "U.S. Court of Appeals for the D.C. Circuit", sourceUrl: "https://media.cadc.uscourts.gov/opinions/docs/2023/08/22-1142-2014527.pdf",
      },
      marketEvent("recovery-40k", "2023-12-04T00:00:00Z", "Bitcoin вернулся выше 40 000 долларов", "Цена продолжила восстановление на ожиданиях биржевых продуктов и смягчения финансовых условий.", "Когда событие ещё не произошло, цена может уже отражать надежду на него. Покупка ожидания несёт риск разочарования даже после хорошей новости.", ["BTC", "ETH", "SOL"]),
      {
        id: "spot-bitcoin-etp", at: "2024-01-10T00:00:00Z", title: "SEC разрешила несколько спотовых продуктов на Bitcoin",
        summary: "Американские биржи получили разрешение листинговать продукты, которые дают доступ к цене Bitcoin через обычный брокерский счёт.",
        context: "Новый канал упрощает доступ, но SEC отдельно подчеркнула: разрешение продукта не является одобрением Bitcoin как вложения.",
        category: "REGULATION", affectedAssets: ["BTC"], sourceName: "U.S. Securities and Exchange Commission", sourceUrl: "https://www.sec.gov/newsroom/speeches-statements/gensler-statement-spot-bitcoin-011023",
      },
      marketEvent("new-ath-2024", "2024-03-13T00:00:00Z", "Bitcoin обновил исторический максимум", "После запуска биржевых продуктов цена превысила вершину 2021 года ещё до следующего халвинга.", "Новый максимум не делает падение невозможным. После большого роста полезно вернуть портфель к выбранным долям, а не повышать риск из-за уверенности.", ["BTC", "ETH", "SOL"]),
      {
        id: "halving-2024", at: "2024-04-20T00:00:00Z", title: "Выпуск новых Bitcoin снова уменьшился вдвое",
        summary: "На блоке 840 000 награда майнерам снизилась с 6,25 до 3,125 BTC.",
        context: "Халвинг известен заранее и не является сюрпризом. Цена после него зависит от спроса и условий рынка, а не только от нового выпуска.",
        category: "TECHNOLOGY", affectedAssets: ["BTC"], sourceName: "Bitcoin block 840 000", sourceUrl: "https://mempool.space/block-height/840000",
      },
      {
        id: "ether-etp-rule-approval", at: "2024-05-23T00:00:00Z", title: "SEC разрешила правила для спотовых продуктов на Ether",
        summary: "Регулятор одобрил изменения правил бирж, необходимые для листинга продуктов, которые держат Ether.",
        context: "Одобрение правил — важный этап, но торговля началась позже после готовности документов конкретных фондов.",
        category: "REGULATION", affectedAssets: ["ETH"], sourceName: "U.S. Securities and Exchange Commission", sourceUrl: "https://www.sec.gov/files/rules/sro/nysearca/2024/34-100224.pdf",
      },
      {
        id: "ether-etp-trading", at: "2024-07-23T00:00:00Z", title: "Спотовые продукты на Ether начали торговаться",
        summary: "Несколько американских биржевых продуктов открыли инвесторам доступ к цене ETH через обычные счета.",
        context: "Запуск расширяет доступ и одновременно создаёт новые потоки покупок и продаж. Первый день торговли не задаёт долгий результат.",
        category: "MARKET", affectedAssets: ["ETH"], sourceName: "SEC filing: Grayscale Ethereum Trust", sourceUrl: "https://www.sec.gov/Archives/edgar/data/1725210/000095017024085501/etheeth_press_release_7.htm",
      },
      marketEvent("bitcoin-100k-2024", "2024-12-05T00:00:00Z", "Bitcoin впервые прошёл 100 000 долларов", "Круглая отметка привлекла новую волну внимания после выборов в США и ожиданий изменения регулирования.", "Круглое число психологически заметно, но не меняет свойства актива. Решение лучше связывать с целью и долей портфеля, а не с красивой отметкой.", ["BTC", "ETH", "SOL"]),
    ],
    dataSource: DATA_SOURCE,
  },
  {
    id: "modern-2024-2025",
    version: "1.0.0",
    title: "Регулирование и информационный шум",
    description: "Завершённый период с июля 2024 по июль 2025: политика, взломы, резкие ожидания и несколько конкурирующих активов.",
    startAt: "2024-07-01T00:00:00Z",
    endAt: "2025-07-01T00:00:00Z",
    startingBalanceRub: 100_000,
    difficulty: "ADVANCED",
    educationalFocus: ["Отделять документ от заголовка", "Оценивать риск хранения на площадке", "Не менять план после каждого политического заявления"],
    benchmark: { kind: "BUY_AND_HOLD", assetSymbol: "BTC", label: "Купить Bitcoin в начале и держать" },
    durationMs: 6 * 60_000,
    assets: [asset("modern-2024-2025", "BTC", "Bitcoin", "#f5a13a"), asset("modern-2024-2025", "ETH", "Ethereum", "#718bd5"), asset("modern-2024-2025", "SOL", "Solana", "#6f52e5")],
    events: [
      {
        id: "modern-ether-etp", at: "2024-07-23T00:00:00Z", title: "В США началась торговля продуктами на Ether",
        summary: "Инвесторы получили новый регулируемый способ следить за ценой ETH без самостоятельного хранения монет.",
        context: "Продукт убирает часть технических трудностей, но оставляет риск цены и добавляет комиссии и правила посредника.",
        category: "MARKET", affectedAssets: ["ETH"], sourceName: "SEC filing: Grayscale Ethereum Trust", sourceUrl: "https://www.sec.gov/Archives/edgar/data/1725210/000095017024085501/etheeth_press_release_7.htm",
      },
      {
        id: "august-selloff-2024", at: "2024-08-05T00:00:00Z", title: "Рискованные рынки резко упали за один день",
        summary: "Слабые данные по занятости в США усилили тревогу на мировых рынках; криптоактивы тоже быстро подешевели.",
        context: "Когда разные рынки падают вместе, причина может быть не внутри конкретной сети. Продажа по одному страшному заголовку может закрепить временный убыток.",
        category: "WORLD", affectedAssets: ["BTC", "ETH", "SOL"], sourceName: "Federal Reserve, протокол заседания сентября 2024", sourceUrl: "https://www.federalreserve.gov/monetarypolicy/fomcminutes20240918.htm",
      },
      {
        id: "fed-cut-2024", at: "2024-09-18T00:00:00Z", title: "ФРС снизила ставку на половину процентного пункта",
        summary: "После долгого периода высоких ставок центральный банк США начал смягчать денежную политику.",
        context: "Более дешёвые деньги могут поддерживать спрос на риск, но рынок часто ожидает решение заранее. Хорошая новость не гарантирует рост после публикации.",
        category: "WORLD", affectedAssets: ["BTC", "ETH", "SOL"], sourceName: "Federal Reserve", sourceUrl: "https://www.federalreserve.gov/newsevents/pressreleases/monetary20240918a.htm",
      },
      marketEvent("us-election-2024", "2024-11-06T00:00:00Z", "Рынок резко отреагировал на выборы в США", "Участники стали закладывать более дружелюбный подход новой администрации к цифровым активам.", "Политические ожидания меняются быстрее законов. Полезно проверить, что уже принято, а что пока является обещанием или догадкой рынка.", ["BTC", "ETH", "SOL"]),
      {
        id: "gensler-departure", at: "2024-11-21T00:00:00Z", title: "Глава SEC объявил дату ухода",
        summary: "Гэри Генслер сообщил, что покинет комиссию 20 января 2025 года.",
        context: "Смена руководителя может изменить приоритеты, но действующие законы и судебные дела не исчезают в один день.",
        category: "REGULATION", affectedAssets: ["BTC", "ETH", "SOL"], sourceName: "U.S. Securities and Exchange Commission", sourceUrl: "https://www.sec.gov/newsroom/press-releases/2024-182",
      },
      marketEvent("modern-bitcoin-100k", "2024-12-05T00:00:00Z", "Bitcoin впервые поднялся выше 100 000 долларов", "Круглая отметка усилила внимание СМИ и приток новых участников.", "Большая цифра создаёт ощущение подтверждённого успеха. Но будущая доходность начинается с текущей цены, а не с истории прошлого роста.", ["BTC", "ETH", "SOL"]),
      {
        id: "sec-crypto-task-force", at: "2025-01-21T00:00:00Z", title: "SEC создала рабочую группу по криптоактивам",
        summary: "Комиссия объявила команду для разработки более ясного подхода к регистрации, раскрытию информации и применению правил.",
        context: "Рабочая группа — начало процесса, а не готовые правила. Заголовок может звучать сильнее, чем реальное немедленное изменение.",
        category: "REGULATION", affectedAssets: ["BTC", "ETH", "SOL"], sourceName: "U.S. Securities and Exchange Commission", sourceUrl: "https://www.sec.gov/newsroom/press-releases/2025-30",
      },
      {
        id: "digital-assets-order", at: "2025-01-23T00:00:00Z", title: "Белый дом поручил подготовить рамки для цифровых активов",
        summary: "Указ создал рабочую группу, запретил продвигать государственную цифровую валюту и потребовал изучить запас цифровых активов.",
        context: "Указ задаёт направление работы. Между направлением, правилами и их практическим исполнением могут пройти месяцы.",
        category: "REGULATION", affectedAssets: ["BTC", "ETH", "SOL"], sourceName: "The White House", sourceUrl: "https://www.whitehouse.gov/presidential-actions/2025/01/strengthening-american-leadership-in-digital-financial-technology/",
      },
      {
        id: "bybit-hack", at: "2025-02-21T00:00:00Z", title: "У Bybit похитили активы примерно на 1,5 млрд долларов",
        summary: "Злоумышленники вывели виртуальные активы с площадки; позднее ФБР связало атаку с группой из КНДР.",
        context: "Даже крупная площадка может стать целью сложной атаки. Важно заранее решить, какую сумму допустимо держать у одного посредника.",
        category: "SECURITY", affectedAssets: ["ETH", "BTC"], sourceName: "Federal Bureau of Investigation", sourceUrl: "https://www.fbi.gov/investigate/cyber/alerts/2025/north-korea-responsible-for-1-5-billion-bybit-hack",
      },
      {
        id: "strategic-bitcoin-reserve", at: "2025-03-06T00:00:00Z", title: "США создали стратегический резерв Bitcoin",
        summary: "Указ предусмотрел хранение конфискованных государством BTC и отдельный запас других цифровых активов.",
        context: "Резерв в основном собирается из уже принадлежащих государству активов. Это не равно немедленной покупке большого объёма на рынке.",
        category: "REGULATION", affectedAssets: ["BTC", "ETH", "SOL"], sourceName: "The White House", sourceUrl: "https://www.whitehouse.gov/presidential-actions/2025/03/establishment-of-the-strategic-bitcoin-reserve-and-united-states-digital-asset-stockpile/",
      },
      {
        id: "tariff-shock-2025", at: "2025-04-02T00:00:00Z", title: "Новые пошлины усилили неопределённость на мировых рынках",
        summary: "США объявили широкие взаимные тарифы, после чего ожидания по росту экономики и инфляции быстро менялись.",
        context: "Криптоактивы торгуются круглосуточно и часто первыми отражают общий страх. Быстрая реакция не означает, что рынок правильно оценил долгий эффект.",
        category: "WORLD", affectedAssets: ["BTC", "ETH", "SOL"], sourceName: "The White House", sourceUrl: "https://www.whitehouse.gov/presidential-actions/2025/04/regulating-imports-with-a-reciprocal-tariff-to-rectify-trade-practices-that-contribute-to-large-and-persistent-annual-united-states-goods-trade-deficits/",
      },
      {
        id: "genius-senate", at: "2025-06-17T00:00:00Z", title: "Сенат США одобрил правила для платёжных стейблкоинов",
        summary: "Законопроект GENIUS Act прошёл Сенат 68 голосами против 30 и перешёл к следующему этапу.",
        context: "Голосование одной палаты ещё не завершает принятие закона. В момент новости участники торгуют вероятность будущих шагов.",
        category: "REGULATION", affectedAssets: ["BTC", "ETH", "SOL", "USDC", "USDT"], sourceName: "United States Senate", sourceUrl: "https://www.senate.gov/legislative/LIS/roll_call_votes/vote1191/vote_119_1_00318.htm",
      },
    ],
    dataSource: DATA_SOURCE,
  },
];
